import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { generateManagedArtifacts } from "@/lib/setup/generator";

describe("generateManagedArtifacts feature removal", () => {
  it("removes managed files for disabled feature", async () => {
    const tempDir = await mkdtemp(path.join(os.tmpdir(), "setup-remove-"));

    try {
      const analyticsDir = path.join(
        tempDir,
        "src/features/generated/analytics",
      );
      await mkdir(analyticsDir, { recursive: true });
      const analyticsFile = path.join(analyticsDir, "index.ts");
      await writeFile(
        analyticsFile,
        "// @generated by pnpm setup - DO NOT EDIT\nexport const analytics = true;\n",
        "utf8",
      );

      await generateManagedArtifacts(
        {
          version: 1,
          provider: "supabase",
          features: {
            auth: true,
            analytics: false,
            errorReporting: true,
            pushNotifications: false,
            payments: false,
          },
        },
        tempDir,
      );

      await expect(readFile(analyticsFile, "utf8")).rejects.toThrow();
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  });
});
