import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { generateManagedArtifacts } from "@/lib/setup/generator";

describe("generateManagedArtifacts", () => {
  it("generates provider and feature managed files", async () => {
    const tempDir = await mkdtemp(path.join(os.tmpdir(), "setup-gen-"));

    try {
      const out = await generateManagedArtifacts(
        {
          version: 1,
          provider: "firebase",
          features: {
            auth: true,
            analytics: false,
            errorReporting: true,
            pushNotifications: false,
            payments: false,
          },
        },
        tempDir,
      );

      expect(out.created).toContain(
        "src/lib/setup/generated/provider-selection.ts",
      );
      expect(out.created).toContain(
        "src/lib/api/providers/generated/adapter-resolver.ts",
      );

      const generatedProvider = await readFile(
        path.join(tempDir, "src/lib/setup/generated/provider-selection.ts"),
        "utf8",
      );

      expect(generatedProvider).toContain("@generated by pnpm setup");
      expect(generatedProvider).toContain("firebase");
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  });
});
