import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const GENERATED_MARKER = "// @generated by pnpm setup - DO NOT EDIT";

const defaultConfig = {
  version: 1,
  provider: "supabase",
  features: {
    auth: true,
    analytics: true,
    errorReporting: true,
    pushNotifications: true,
    payments: false,
  },
};

const PROVIDER_ENV_KEYS = {
  supabase: ["EXPO_PUBLIC_SUPABASE_URL", "EXPO_PUBLIC_SUPABASE_ANON_KEY"],
  convex: ["EXPO_PUBLIC_CONVEX_URL"],
  firebase: [
    "EXPO_PUBLIC_FIREBASE_API_KEY",
    "EXPO_PUBLIC_FIREBASE_PROJECT_ID",
    "EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN",
  ],
  custom: ["EXPO_PUBLIC_API_URL"],
};

const FEATURE_ENV_KEYS = {
  analytics: ["EXPO_PUBLIC_FLAGS_ENDPOINT", "EXPO_PUBLIC_POSTHOG_API_KEY"],
  errorReporting: ["EXPO_PUBLIC_SENTRY_DSN"],
};

function buildEnvKeys(provider, features) {
  const keys = new Set(PROVIDER_ENV_KEYS[provider] ?? []);
  for (const [feature, enabled] of Object.entries(features)) {
    if (!enabled) continue;
    for (const key of FEATURE_ENV_KEYS[feature] ?? []) {
      keys.add(key);
    }
  }
  return Array.from(keys).sort();
}

const featureToDir = {
  auth: "auth",
  analytics: "analytics",
  errorReporting: "error-reporting",
  pushNotifications: "push-notifications",
  payments: "payments",
};

async function loadCurrentConfig(rootDir) {
  try {
    const raw = await readFile(path.join(rootDir, "app.setup.json"), "utf8");
    const parsed = JSON.parse(raw);
    return parsed?.version === 1 ? parsed : defaultConfig;
  } catch {
    return defaultConfig;
  }
}

async function writeManagedFile(filePath, content) {
  try {
    const existing = await readFile(filePath, "utf8");
    if (!existing.includes(GENERATED_MARKER)) {
      await writeFile(`${filePath}.setup.bak`, existing, "utf8");
      return;
    }
  } catch {
    // file does not exist
  }
  await writeFile(filePath, content, "utf8");
}

export async function runSetup({
  rootDir = process.cwd(),
  prompts,
  presetProvider,
  presetFeatures,
  dryRun = false,
}) {
  const previous = await loadCurrentConfig(rootDir);
  const provider = presetProvider ?? await prompts.selectProvider(previous.provider);
  const features = presetFeatures ?? await prompts.selectFeatures(previous.features);
  const next = { version: 1, provider, features };

  if (dryRun) {
    return { previous, next, applied: false };
  }

  await writeFile(path.join(rootDir, "app.setup.json"), `${JSON.stringify(next, null, 2)}\n`);

  const setupGeneratedDir = path.join(rootDir, "src/lib/setup/generated");
  const providerGeneratedDir = path.join(rootDir, "src/lib/api/providers/generated");
  const featuresGeneratedDir = path.join(rootDir, "src/features/generated");
  const appGeneratedDir = path.join(rootDir, "src/app/generated");

  await mkdir(setupGeneratedDir, { recursive: true });
  await mkdir(providerGeneratedDir, { recursive: true });
  await mkdir(featuresGeneratedDir, { recursive: true });
  await mkdir(appGeneratedDir, { recursive: true });

  await writeManagedFile(
    path.join(setupGeneratedDir, "provider-selection.ts"),
    `${GENERATED_MARKER}\nexport const selectedProvider = "${provider}" as const;\n`,
  );

  const featureLines = Object.entries(features)
    .map(([k, v]) => `  ${k}: ${v},`);
  await writeManagedFile(
    path.join(setupGeneratedDir, "feature-flags.ts"),
    `${GENERATED_MARKER}\nexport const setupEnabledFeatures = {\n${featureLines.join("\n")}\n} as const;\n`,
  );

  const envKeys = buildEnvKeys(provider, features);
  await writeManagedFile(
    path.join(setupGeneratedDir, "env-contract.ts"),
    `${GENERATED_MARKER}\nexport const setupEnvContract = {\n  requiredKeys: [${envKeys.map((k) => `"${k}"`).join(", ")}],\n} as const;\n`,
  );

  await writeManagedFile(
    path.join(providerGeneratedDir, "adapter-resolver.ts"),
    `${GENERATED_MARKER}\nimport { convexAdapter } from "@/lib/api/providers/convex/adapter";\nimport { customAdapter } from "@/lib/api/providers/custom/adapter";\nimport { firebaseAdapter } from "@/lib/api/providers/firebase/adapter";\nimport { supabaseAdapter } from "@/lib/api/providers/supabase/adapter";\nimport { selectedProvider } from "@/lib/setup/generated/provider-selection";\n\nconst providerMap = {\n  supabase: supabaseAdapter,\n  convex: convexAdapter,\n  firebase: firebaseAdapter,\n  custom: customAdapter,\n} as const;\n\nexport function resolveApiProviderAdapter() {\n  return providerMap[selectedProvider] ?? supabaseAdapter;\n}\n`,
  );

  if (provider === "custom") {
    const customDir = path.join(rootDir, "src/lib/api/providers/custom");
    await mkdir(customDir, { recursive: true });
    await writeManagedFile(
      path.join(customDir, "adapter.ts"),
      `${GENERATED_MARKER}\nimport type { ApiProviderAdapter } from "@/lib/api/providers/types";\n\nexport const customAdapter: ApiProviderAdapter = {\n  id: "custom",\n  async request() {\n    // TODO: implement custom provider request logic\n    return { ok: false, error: new Error("Custom provider adapter is not implemented") };\n  },\n};\n`,
    );
    await writeManagedFile(
      path.join(customDir, "README.md"),
      `${GENERATED_MARKER}\n# Custom Provider Adapter\n\nTODO: implement custom provider behavior in adapter.ts.\n`,
    );
  }

  for (const [feature, enabled] of Object.entries(features)) {
    const dirName = featureToDir[feature];
    const featureDir = path.join(featuresGeneratedDir, dirName);
    const appDir = path.join(appGeneratedDir, dirName);
    if (!enabled) {
      await rm(featureDir, { recursive: true, force: true });
      await rm(appDir, { recursive: true, force: true });
      continue;
    }

    await mkdir(featureDir, { recursive: true });
    await mkdir(appDir, { recursive: true });
    await writeManagedFile(
      path.join(featureDir, "index.ts"),
      `${GENERATED_MARKER}\nexport const ${feature}Enabled = true;\n`,
    );
    await writeManagedFile(
      path.join(appDir, "index.ts"),
      `${GENERATED_MARKER}\nexport const ${feature}RouteEnabled = true;\n`,
    );
  }

  return { previous, next, applied: true };
}
