import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const GENERATED_MARKER = "// @generated by pnpm setup - DO NOT EDIT";

const defaultConfig = {
  version: 1,
  provider: "supabase",
  features: {
    auth: true,
    analytics: true,
    errorReporting: true,
    pushNotifications: true,
    payments: false,
  },
};

const featureToDir = {
  auth: "auth",
  analytics: "analytics",
  errorReporting: "error-reporting",
  pushNotifications: "push-notifications",
  payments: "payments",
};

async function loadCurrentConfig(rootDir) {
  try {
    const raw = await readFile(path.join(rootDir, "app.setup.json"), "utf8");
    const parsed = JSON.parse(raw);
    return parsed?.version === 1 ? parsed : defaultConfig;
  } catch {
    return defaultConfig;
  }
}

async function writeManagedFile(filePath, content) {
  try {
    const existing = await readFile(filePath, "utf8");
    if (!existing.includes(GENERATED_MARKER)) {
      await writeFile(`${filePath}.setup.bak`, existing, "utf8");
      return;
    }
  } catch {
    // file does not exist
  }
  await writeFile(filePath, content, "utf8");
}

export async function runSetup({ rootDir = process.cwd(), prompts }) {
  const current = await loadCurrentConfig(rootDir);
  const provider = await prompts.selectProvider(current.provider);
  const features = await prompts.selectFeatures(current.features);
  const next = { version: 1, provider, features };

  await writeFile(path.join(rootDir, "app.setup.json"), `${JSON.stringify(next, null, 2)}\n`);

  const setupGeneratedDir = path.join(rootDir, "src/lib/setup/generated");
  const providerGeneratedDir = path.join(rootDir, "src/lib/api/providers/generated");
  const featuresGeneratedDir = path.join(rootDir, "src/features/generated");
  const appGeneratedDir = path.join(rootDir, "src/app/generated");

  await mkdir(setupGeneratedDir, { recursive: true });
  await mkdir(providerGeneratedDir, { recursive: true });
  await mkdir(featuresGeneratedDir, { recursive: true });
  await mkdir(appGeneratedDir, { recursive: true });

  await writeManagedFile(
    path.join(setupGeneratedDir, "provider-selection.ts"),
    `${GENERATED_MARKER}\nexport const selectedProvider = ${JSON.stringify(provider)} as const;\n`,
  );

  await writeManagedFile(
    path.join(setupGeneratedDir, "feature-flags.ts"),
    `${GENERATED_MARKER}\nexport const setupEnabledFeatures = ${JSON.stringify(features, null, 2)} as const;\n`,
  );

  await writeManagedFile(
    path.join(providerGeneratedDir, "adapter-resolver.ts"),
    `${GENERATED_MARKER}\nimport { convexAdapter } from "@/lib/api/providers/convex/adapter";\nimport { customAdapter } from "@/lib/api/providers/custom/adapter";\nimport { firebaseAdapter } from "@/lib/api/providers/firebase/adapter";\nimport { supabaseAdapter } from "@/lib/api/providers/supabase/adapter";\nimport { selectedProvider } from "@/lib/setup/generated/provider-selection";\n\nconst providerMap = {\n  supabase: supabaseAdapter,\n  convex: convexAdapter,\n  firebase: firebaseAdapter,\n  custom: customAdapter,\n} as const;\n\nexport function resolveApiProviderAdapter() {\n  return providerMap[selectedProvider] ?? supabaseAdapter;\n}\n`,
  );

  if (provider === "custom") {
    const customDir = path.join(rootDir, "src/lib/api/providers/custom");
    await mkdir(customDir, { recursive: true });
    await writeManagedFile(
      path.join(customDir, "adapter.ts"),
      `${GENERATED_MARKER}\nimport type { ApiProviderAdapter } from "@/lib/api/providers/types";\n\nexport const customAdapter: ApiProviderAdapter = {\n  id: "custom",\n  async request() {\n    // TODO: implement custom provider request logic\n    return { ok: false, error: new Error("Custom provider adapter is not implemented") };\n  },\n};\n`,
    );
    await writeManagedFile(
      path.join(customDir, "README.md"),
      `${GENERATED_MARKER}\n# Custom Provider Adapter\n\nTODO: implement custom provider behavior in adapter.ts.\n`,
    );
  }

  for (const [feature, enabled] of Object.entries(features)) {
    const dirName = featureToDir[feature];
    const featureDir = path.join(featuresGeneratedDir, dirName);
    const appDir = path.join(appGeneratedDir, dirName);
    if (!enabled) {
      await rm(featureDir, { recursive: true, force: true });
      await rm(appDir, { recursive: true, force: true });
      continue;
    }

    await mkdir(featureDir, { recursive: true });
    await mkdir(appDir, { recursive: true });
    await writeManagedFile(
      path.join(featureDir, "index.ts"),
      `${GENERATED_MARKER}\nexport const ${feature}Enabled = true;\n`,
    );
    await writeManagedFile(
      path.join(appDir, "index.ts"),
      `${GENERATED_MARKER}\nexport const ${feature}RouteEnabled = true;\n`,
    );
  }

  return next;
}
