// @generated by pnpm setup - DO NOT EDIT
import type { ApiProviderAdapter } from "@/lib/api/providers/types";

export const customAdapter: ApiProviderAdapter = {
  id: "custom",
  async request() {
    // TODO: implement custom provider request logic
    return {
      ok: false,
      error: new Error("Custom provider adapter is not implemented"),
    };
  },
};
